import Blog1 from '../../Assets/blog/blog1.jpg'
import Blog2 from '../../Assets/blog/blog2.jpg'
import Blog3 from '../../Assets/blog/blog3.jpg'

export const BlogData = [
    {img:Blog1,date:'22 jan 2023',comment: 0,title:'1Exploring Spirituality, Culture, and Devotion',desc:'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci…'},
    {img:Blog2,date:'22 jan 2023',comment: 0,title:'2Journey Through Faith, Rituals, and Sacred Stories',desc:'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci…'},
    {img:Blog3,date:'22 jan 2023',comment: 0,title:'3Navigating Spiritual Bliss in Ten Soulful Chapters',desc:'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci…'},
    {img:Blog1,date:'22 jan 2023',comment: 0,title:'4Exploring Spirituality, Culture, and Devotion',desc:'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci…'},
    {img:Blog2,date:'22 jan 2023',comment: 0,title:'5Journey Through Faith, Rituals, and Sacred Stories',desc:'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci…'},
    {img:Blog3,date:'22 jan 2023',comment: 0,title:'6Navigating Spiritual Bliss in Ten Soulful Chapters',desc:'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci…'},
    {img:Blog1,date:'22 jan 2023',comment: 0,title:'7Exploring Spirituality, Culture, and Devotion',desc:'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci…'},
    {img:Blog2,date:'22 jan 2023',comment: 0,title:'8Journey Through Faith, Rituals, and Sacred Stories',desc:'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci…'},
    {img:Blog3,date:'22 jan 2023',comment: 0,title:'9Navigating Spiritual Bliss in Ten Soulful Chapters',desc:'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci…'},
    {img:Blog1,date:'22 jan 2023',comment: 0,title:'10Exploring Spirituality, Culture, and Devotion',desc:'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci…'},
    {img:Blog2,date:'22 jan 2023',comment: 0,title:'11Journey Through Faith, Rituals, and Sacred Stories',desc:'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci…'},
    {img:Blog3,date:'22 jan 2023',comment: 0,title:'12Navigating Spiritual Bliss in Ten Soulful Chapters',desc:'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci…'},
    {img:Blog3,date:'22 jan 2023',comment: 0,title:'13Navigating Spiritual Bliss in Ten Soulful Chapters',desc:'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci…'},
]
